# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/hanpengfei/dev/c-algorithm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/hanpengfei/dev/c-algorithm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hanpengfei/dev/c-algorithm/CMakeFiles /Users/hanpengfei/dev/c-algorithm/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hanpengfei/dev/c-algorithm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named array-list-test

# Build rule for target.
array-list-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 array-list-test
.PHONY : array-list-test

# fast build rule for target.
array-list-test/fast:
	$(MAKE) -f CMakeFiles/array-list-test.dir/build.make CMakeFiles/array-list-test.dir/build
.PHONY : array-list-test/fast

src/collection/collection.o: src/collection/collection.c.o

.PHONY : src/collection/collection.o

# target to build an object file
src/collection/collection.c.o:
	$(MAKE) -f CMakeFiles/array-list-test.dir/build.make CMakeFiles/array-list-test.dir/src/collection/collection.c.o
.PHONY : src/collection/collection.c.o

src/collection/collection.i: src/collection/collection.c.i

.PHONY : src/collection/collection.i

# target to preprocess a source file
src/collection/collection.c.i:
	$(MAKE) -f CMakeFiles/array-list-test.dir/build.make CMakeFiles/array-list-test.dir/src/collection/collection.c.i
.PHONY : src/collection/collection.c.i

src/collection/collection.s: src/collection/collection.c.s

.PHONY : src/collection/collection.s

# target to generate assembly for a file
src/collection/collection.c.s:
	$(MAKE) -f CMakeFiles/array-list-test.dir/build.make CMakeFiles/array-list-test.dir/src/collection/collection.c.s
.PHONY : src/collection/collection.c.s

src/collection/list/array-list.o: src/collection/list/array-list.c.o

.PHONY : src/collection/list/array-list.o

# target to build an object file
src/collection/list/array-list.c.o:
	$(MAKE) -f CMakeFiles/array-list-test.dir/build.make CMakeFiles/array-list-test.dir/src/collection/list/array-list.c.o
.PHONY : src/collection/list/array-list.c.o

src/collection/list/array-list.i: src/collection/list/array-list.c.i

.PHONY : src/collection/list/array-list.i

# target to preprocess a source file
src/collection/list/array-list.c.i:
	$(MAKE) -f CMakeFiles/array-list-test.dir/build.make CMakeFiles/array-list-test.dir/src/collection/list/array-list.c.i
.PHONY : src/collection/list/array-list.c.i

src/collection/list/array-list.s: src/collection/list/array-list.c.s

.PHONY : src/collection/list/array-list.s

# target to generate assembly for a file
src/collection/list/array-list.c.s:
	$(MAKE) -f CMakeFiles/array-list-test.dir/build.make CMakeFiles/array-list-test.dir/src/collection/list/array-list.c.s
.PHONY : src/collection/list/array-list.c.s

src/collection/list/list-iterator.o: src/collection/list/list-iterator.c.o

.PHONY : src/collection/list/list-iterator.o

# target to build an object file
src/collection/list/list-iterator.c.o:
	$(MAKE) -f CMakeFiles/array-list-test.dir/build.make CMakeFiles/array-list-test.dir/src/collection/list/list-iterator.c.o
.PHONY : src/collection/list/list-iterator.c.o

src/collection/list/list-iterator.i: src/collection/list/list-iterator.c.i

.PHONY : src/collection/list/list-iterator.i

# target to preprocess a source file
src/collection/list/list-iterator.c.i:
	$(MAKE) -f CMakeFiles/array-list-test.dir/build.make CMakeFiles/array-list-test.dir/src/collection/list/list-iterator.c.i
.PHONY : src/collection/list/list-iterator.c.i

src/collection/list/list-iterator.s: src/collection/list/list-iterator.c.s

.PHONY : src/collection/list/list-iterator.s

# target to generate assembly for a file
src/collection/list/list-iterator.c.s:
	$(MAKE) -f CMakeFiles/array-list-test.dir/build.make CMakeFiles/array-list-test.dir/src/collection/list/list-iterator.c.s
.PHONY : src/collection/list/list-iterator.c.s

src/collection/list/list.o: src/collection/list/list.c.o

.PHONY : src/collection/list/list.o

# target to build an object file
src/collection/list/list.c.o:
	$(MAKE) -f CMakeFiles/array-list-test.dir/build.make CMakeFiles/array-list-test.dir/src/collection/list/list.c.o
.PHONY : src/collection/list/list.c.o

src/collection/list/list.i: src/collection/list/list.c.i

.PHONY : src/collection/list/list.i

# target to preprocess a source file
src/collection/list/list.c.i:
	$(MAKE) -f CMakeFiles/array-list-test.dir/build.make CMakeFiles/array-list-test.dir/src/collection/list/list.c.i
.PHONY : src/collection/list/list.c.i

src/collection/list/list.s: src/collection/list/list.c.s

.PHONY : src/collection/list/list.s

# target to generate assembly for a file
src/collection/list/list.c.s:
	$(MAKE) -f CMakeFiles/array-list-test.dir/build.make CMakeFiles/array-list-test.dir/src/collection/list/list.c.s
.PHONY : src/collection/list/list.c.s

src/test.o: src/test.c.o

.PHONY : src/test.o

# target to build an object file
src/test.c.o:
	$(MAKE) -f CMakeFiles/array-list-test.dir/build.make CMakeFiles/array-list-test.dir/src/test.c.o
.PHONY : src/test.c.o

src/test.i: src/test.c.i

.PHONY : src/test.i

# target to preprocess a source file
src/test.c.i:
	$(MAKE) -f CMakeFiles/array-list-test.dir/build.make CMakeFiles/array-list-test.dir/src/test.c.i
.PHONY : src/test.c.i

src/test.s: src/test.c.s

.PHONY : src/test.s

# target to generate assembly for a file
src/test.c.s:
	$(MAKE) -f CMakeFiles/array-list-test.dir/build.make CMakeFiles/array-list-test.dir/src/test.c.s
.PHONY : src/test.c.s

test/collection/collection-test.o: test/collection/collection-test.c.o

.PHONY : test/collection/collection-test.o

# target to build an object file
test/collection/collection-test.c.o:
	$(MAKE) -f CMakeFiles/array-list-test.dir/build.make CMakeFiles/array-list-test.dir/test/collection/collection-test.c.o
.PHONY : test/collection/collection-test.c.o

test/collection/collection-test.i: test/collection/collection-test.c.i

.PHONY : test/collection/collection-test.i

# target to preprocess a source file
test/collection/collection-test.c.i:
	$(MAKE) -f CMakeFiles/array-list-test.dir/build.make CMakeFiles/array-list-test.dir/test/collection/collection-test.c.i
.PHONY : test/collection/collection-test.c.i

test/collection/collection-test.s: test/collection/collection-test.c.s

.PHONY : test/collection/collection-test.s

# target to generate assembly for a file
test/collection/collection-test.c.s:
	$(MAKE) -f CMakeFiles/array-list-test.dir/build.make CMakeFiles/array-list-test.dir/test/collection/collection-test.c.s
.PHONY : test/collection/collection-test.c.s

test/collection/list/array-list-test.o: test/collection/list/array-list-test.c.o

.PHONY : test/collection/list/array-list-test.o

# target to build an object file
test/collection/list/array-list-test.c.o:
	$(MAKE) -f CMakeFiles/array-list-test.dir/build.make CMakeFiles/array-list-test.dir/test/collection/list/array-list-test.c.o
.PHONY : test/collection/list/array-list-test.c.o

test/collection/list/array-list-test.i: test/collection/list/array-list-test.c.i

.PHONY : test/collection/list/array-list-test.i

# target to preprocess a source file
test/collection/list/array-list-test.c.i:
	$(MAKE) -f CMakeFiles/array-list-test.dir/build.make CMakeFiles/array-list-test.dir/test/collection/list/array-list-test.c.i
.PHONY : test/collection/list/array-list-test.c.i

test/collection/list/array-list-test.s: test/collection/list/array-list-test.c.s

.PHONY : test/collection/list/array-list-test.s

# target to generate assembly for a file
test/collection/list/array-list-test.c.s:
	$(MAKE) -f CMakeFiles/array-list-test.dir/build.make CMakeFiles/array-list-test.dir/test/collection/list/array-list-test.c.s
.PHONY : test/collection/list/array-list-test.c.s

test/collection/list/list-test.o: test/collection/list/list-test.c.o

.PHONY : test/collection/list/list-test.o

# target to build an object file
test/collection/list/list-test.c.o:
	$(MAKE) -f CMakeFiles/array-list-test.dir/build.make CMakeFiles/array-list-test.dir/test/collection/list/list-test.c.o
.PHONY : test/collection/list/list-test.c.o

test/collection/list/list-test.i: test/collection/list/list-test.c.i

.PHONY : test/collection/list/list-test.i

# target to preprocess a source file
test/collection/list/list-test.c.i:
	$(MAKE) -f CMakeFiles/array-list-test.dir/build.make CMakeFiles/array-list-test.dir/test/collection/list/list-test.c.i
.PHONY : test/collection/list/list-test.c.i

test/collection/list/list-test.s: test/collection/list/list-test.c.s

.PHONY : test/collection/list/list-test.s

# target to generate assembly for a file
test/collection/list/list-test.c.s:
	$(MAKE) -f CMakeFiles/array-list-test.dir/build.make CMakeFiles/array-list-test.dir/test/collection/list/list-test.c.s
.PHONY : test/collection/list/list-test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... array-list-test"
	@echo "... src/collection/collection.o"
	@echo "... src/collection/collection.i"
	@echo "... src/collection/collection.s"
	@echo "... src/collection/list/array-list.o"
	@echo "... src/collection/list/array-list.i"
	@echo "... src/collection/list/array-list.s"
	@echo "... src/collection/list/list-iterator.o"
	@echo "... src/collection/list/list-iterator.i"
	@echo "... src/collection/list/list-iterator.s"
	@echo "... src/collection/list/list.o"
	@echo "... src/collection/list/list.i"
	@echo "... src/collection/list/list.s"
	@echo "... src/test.o"
	@echo "... src/test.i"
	@echo "... src/test.s"
	@echo "... test/collection/collection-test.o"
	@echo "... test/collection/collection-test.i"
	@echo "... test/collection/collection-test.s"
	@echo "... test/collection/list/array-list-test.o"
	@echo "... test/collection/list/array-list-test.i"
	@echo "... test/collection/list/array-list-test.s"
	@echo "... test/collection/list/list-test.o"
	@echo "... test/collection/list/list-test.i"
	@echo "... test/collection/list/list-test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

